### ISSUE TITLE
[Bug] If I press printScreen multiple times, the program only stores two images.

### ISSUE THREAD

**Issue by jackeryli** [j3soon/PrintScreen#1]
If I press the printscreen in a second for multiple times, it will only store two images. Exactly it should store at least five images for me. I think the iterator of the filename might be wrong.
![20210424_21-36-10](https://user-images.githubusercontent.com/13606995/115960862-4fcc1280-a546-11eb-8c87-614066fcdcbb.png)

**Comment by j3soon** [comment]
Thanks, it's indeed a filename iterator issue. I have never taken more than two screenshots in a second so I never noticed it.

I just performed a hotfix and you can now download the [newer version here](https://github.com/j3soon/PrintScreen/releases/tag/v1.2.0).

Please re-open this issue if the problem persists.

**Comment by jackeryli** [comment]
> Thanks, it's indeed a filename iterator issue. I have never taken more than two screenshots in a second so I never noticed it.
> 
> I just performed a hotfix and you can now download the [newer version here](https://github.com/j3soon/PrintScreen/releases/tag/v1.2.0).
> 
> Please re-open this issue if the problem persists.

It's pretty nice. Thanks.
